//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDelivery.Domain.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExpressDeliveryEntities : DbContext
    {
        public ExpressDeliveryEntities()
            : base("name=ExpressDeliveryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Автомобили> Автомобили { get; set; }
        public virtual DbSet<Города> Города { get; set; }
        public virtual DbSet<Грузы> Грузы { get; set; }
        public virtual DbSet<Заказы> Заказы { get; set; }
        public virtual DbSet<Клиенты> Клиенты { get; set; }
        public virtual DbSet<Маршруты> Маршруты { get; set; }
        public virtual DbSet<Платежи> Платежи { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<Тарифы> Тарифы { get; set; }
        public virtual DbSet<Услуги> Услуги { get; set; }
        public virtual DbSet<Филиалы> Филиалы { get; set; }
        public virtual DbSet<ИсторияОтслеживания> ИсторияОтслеживания { get; set; }
        public virtual DbSet<Комментарии> Комментарии { get; set; }
        public virtual DbSet<Сообщения> Сообщения { get; set; }
        public virtual DbSet<Уведомления> Уведомления { get; set; }
    }
}
