//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDelivery.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Акции
    {
        public int кодАкции { get; set; }
        public string наименованиеАкции { get; set; }
        public string описаниеАкции { get; set; }
        public double скидка { get; set; }
        public System.DateTime датаНачала { get; set; }
        public System.DateTime датаОкончания { get; set; }
    }
}
