//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDelivery.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказы()
        {
            this.Грузы = new HashSet<Грузы>();
        }
    
        public int кодЗаказа { get; set; }
        public System.DateTime датаЗаказа { get; set; }
        public string фиоПолучателя { get; set; }
        public string ГородПолучателя { get; set; }
        public string адресПолучателя { get; set; }
        public string почтовыйИндекс { get; set; }
        public decimal стоимостьЗзаказа { get; set; }
        public string примечаниеКЗаказу { get; set; }
        public int табельныйНомерСотрудника { get; set; }
        public string кодКлиента { get; set; }
        public int кодТарифа { get; set; }
        public Nullable<int> кодУслуги { get; set; }
        public int номерПлатежа { get; set; }
        public int кодМаршрута { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Грузы> Грузы { get; set; }
        public virtual Тарифы Тарифы { get; set; }
        public virtual Клиенты Клиенты { get; set; }
        public virtual Маршруты Маршруты { get; set; }
        public virtual Платежи Платежи { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Услуги Услуги { get; set; }
    }
}
