//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDelivery.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ИсторияОтслеживания
    {
        public int кодЗаписи { get; set; }
        public int кодГруза { get; set; }
        public System.DateTime датаЗаписи { get; set; }
        public string пунктРегистрации { get; set; }
        public string примечание { get; set; }
    
        public virtual Грузы Грузы { get; set; }
    }
}
