//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDelivery.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Комментарии
    {
        public int кодКомментария { get; set; }
        public int кодКлиента { get; set; }
        public string текстКомментария { get; set; }
        public Nullable<int> оценка { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
    }
}
