//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDelivery.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Платежи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Платежи()
        {
            this.Заказы = new HashSet<Заказы>();
        }
    
        public int номерПлатежа { get; set; }
        public string видПлатежнойСистемы { get; set; }
        public System.DateTime датаПлатежа { get; set; }
        public decimal суммаПлатежа { get; set; }
        public string номерСчетаОткуда { get; set; }
        public string номерСчетаКуда { get; set; }
        public double комиссия { get; set; }
        public string примечаниеКПлатежу { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказы> Заказы { get; set; }
    }
}
