//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDelivery.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Уведомления
    {
        public int кодУведомления { get; set; }
        public System.DateTime датаУведомления { get; set; }
        public string темаУведомления { get; set; }
        public string текстУведомления { get; set; }
        public int кодКлиента { get; set; }
        public int табельныйНомер { get; set; }
        public long прочитано { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
