//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDelivery.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Грузы
    {
        public int кодГруза { get; set; }
        public string габаритыГруза { get; set; }
        public double массаГруза { get; set; }
        public string типГруза { get; set; }
        public string статусГруза { get; set; }
        public string номерОтслеживания { get; set; }
        public string примечание { get; set; }
        public int грнАвтомобиля { get; set; }
        public int кодЗаказа { get; set; }
    
        public virtual Автомобили Автомобили { get; set; }
        public virtual Заказы Заказы { get; set; }
    }
}
