//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDelivery.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Маршруты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Маршруты()
        {
            this.Заказы = new HashSet<Заказы>();
        }
    
        public int кодМаршрута { get; set; }
        public string наименованиеМаршрута { get; set; }
        public string пунктОтправления { get; set; }
        public System.DateTime датаОтправления { get; set; }
        public double протяженностьМаршрута { get; set; }
        public string пунктНазначения { get; set; }
        public System.DateTime датаПрибытия { get; set; }
        public double длительностьПеревозки { get; set; }
        public decimal стоимостьПеревозки { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказы> Заказы { get; set; }
    }
}
